# Generated by Django 4.2.5 on 2023-10-04 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='municipios',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='origen',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='resultado',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sector',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sexo',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_paciente',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='setDatos',
            fields=[
                ('FECHA_ACTUALIZACION', models.DateField()),
                ('ID_REGISTRO', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ENTIDAD_UM', models.CharField(choices=[('27', 'TABASCO'), ('12', 'GUERRERO'), ('25', 'SINALOA'), ('17', 'MORELOS'), ('31', 'YUCATÁN'), ('98', 'SE IGNORA'), ('02', 'BAJA CALIFORNIA'), ('14', 'JALISCO'), ('24', 'SAN LUIS POTOSÍ'), ('26', 'SONORA'), ('11', 'GUANAJUATO'), ('06', 'COLIMA'), ('10', 'DURANGO'), ('97', 'NO APLICA'), ('13', 'HIDALGO'), ('29', 'TLAXCALA'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('22', 'QUERÉTARO'), ('23', 'QUINTANA ROO'), ('19', 'NUEVO LEÓN'), ('09', 'CIUDAD DE MÉXICO'), ('15', 'MÉXICO'), ('28', 'TAMAULIPAS'), ('18', 'NAYARIT'), ('20', 'OAXACA'), ('01', 'AGUASCALIENTES'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('04', 'CAMPECHE'), ('08', 'CHIHUAHUA'), ('07', 'CHIAPAS'), ('21', 'PUEBLA'), ('05', 'COAHUILA DE ZARAGOZA'), ('03', 'BAJA CALIFORNIA SUR'), ('32', 'ZACATECAS'), ('99', 'NO ESPECIFICADO'), ('16', 'MICHOACÁN DE OCAMPO')], default='99', max_length=2)),
                ('ENTIDAD_NAC', models.CharField(choices=[('27', 'TABASCO'), ('12', 'GUERRERO'), ('25', 'SINALOA'), ('17', 'MORELOS'), ('31', 'YUCATÁN'), ('98', 'SE IGNORA'), ('02', 'BAJA CALIFORNIA'), ('14', 'JALISCO'), ('24', 'SAN LUIS POTOSÍ'), ('26', 'SONORA'), ('11', 'GUANAJUATO'), ('06', 'COLIMA'), ('10', 'DURANGO'), ('97', 'NO APLICA'), ('13', 'HIDALGO'), ('29', 'TLAXCALA'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('22', 'QUERÉTARO'), ('23', 'QUINTANA ROO'), ('19', 'NUEVO LEÓN'), ('09', 'CIUDAD DE MÉXICO'), ('15', 'MÉXICO'), ('28', 'TAMAULIPAS'), ('18', 'NAYARIT'), ('20', 'OAXACA'), ('01', 'AGUASCALIENTES'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('04', 'CAMPECHE'), ('08', 'CHIHUAHUA'), ('07', 'CHIAPAS'), ('21', 'PUEBLA'), ('05', 'COAHUILA DE ZARAGOZA'), ('03', 'BAJA CALIFORNIA SUR'), ('32', 'ZACATECAS'), ('99', 'NO ESPECIFICADO'), ('16', 'MICHOACÁN DE OCAMPO')], default='99', max_length=2)),
                ('ENTIDAD_RES', models.CharField(choices=[('27', 'TABASCO'), ('12', 'GUERRERO'), ('25', 'SINALOA'), ('17', 'MORELOS'), ('31', 'YUCATÁN'), ('98', 'SE IGNORA'), ('02', 'BAJA CALIFORNIA'), ('14', 'JALISCO'), ('24', 'SAN LUIS POTOSÍ'), ('26', 'SONORA'), ('11', 'GUANAJUATO'), ('06', 'COLIMA'), ('10', 'DURANGO'), ('97', 'NO APLICA'), ('13', 'HIDALGO'), ('29', 'TLAXCALA'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('22', 'QUERÉTARO'), ('23', 'QUINTANA ROO'), ('19', 'NUEVO LEÓN'), ('09', 'CIUDAD DE MÉXICO'), ('15', 'MÉXICO'), ('28', 'TAMAULIPAS'), ('18', 'NAYARIT'), ('20', 'OAXACA'), ('01', 'AGUASCALIENTES'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('04', 'CAMPECHE'), ('08', 'CHIHUAHUA'), ('07', 'CHIAPAS'), ('21', 'PUEBLA'), ('05', 'COAHUILA DE ZARAGOZA'), ('03', 'BAJA CALIFORNIA SUR'), ('32', 'ZACATECAS'), ('99', 'NO ESPECIFICADO'), ('16', 'MICHOACÁN DE OCAMPO')], default='99', max_length=2)),
                ('FECHA_INGRESO', models.DateField()),
                ('FECHA_SINTOMAS', models.DateField()),
                ('FECHA_DEF', models.DateField()),
                ('INTUBADO', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('NEUMONIA', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('EDAD', models.IntegerField()),
                ('NACIONALIDAD', models.CharField(choices=[('2', 'extranjera'), ('99', 'no especificado'), ('1', 'mexicana')], default='99', max_length=2)),
                ('EMBARAZO', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('HABLA_LENGUA_INDIG', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('DIABETES', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('EPOC', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('ASMA', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('INMUSUPR', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('HIPERTENSION', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('OTRA_COM', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('CARDIOVASCULAR', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('OBESIDAD', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('RENAL_CRONICA', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('TABAQUISMO', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('OTRO_CASO', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('RESULTADO', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('MIGRANTE', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('PAIS_NACIONALIDAD', models.CharField(choices=[('2', 'extranjera'), ('99', 'no especificado'), ('1', 'mexicana')], default='99', max_length=2)),
                ('PAIS_ORIGEN', models.CharField(choices=[('2', 'extranjera'), ('99', 'no especificado'), ('1', 'mexicana')], default='99', max_length=2)),
                ('UCI', models.CharField(choices=[('98', 'se ignora'), ('1', 'si'), ('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2)),
                ('MUNICIPIO_RES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidIA.municipios')),
                ('ORIGEN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidIA.origen')),
                ('SECTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidIA.sector')),
                ('SEXO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidIA.sexo')),
                ('TIPO_PACIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidIA.tipo_paciente')),
            ],
        ),
    ]
