# Generated by Django 4.2.5 on 2023-10-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidIA', '0002_alter_setdatos_asma_alter_setdatos_cardiovascular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='estados',
            fields=[
                ('clave', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='resultado',
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ASMA',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='CARDIOVASCULAR',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='DIABETES',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EMBARAZO',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_NAC',
            field=models.CharField(choices=[('14', 'JALISCO'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('24', 'SAN LUIS POTOSÍ'), ('01', 'AGUASCALIENTES'), ('25', 'SINALOA'), ('07', 'CHIAPAS'), ('21', 'PUEBLA'), ('09', 'CIUDAD DE MÉXICO'), ('12', 'GUERRERO'), ('13', 'HIDALGO'), ('29', 'TLAXCALA'), ('16', 'MICHOACÁN DE OCAMPO'), ('19', 'NUEVO LEÓN'), ('17', 'MORELOS'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('10', 'DURANGO'), ('20', 'OAXACA'), ('03', 'BAJA CALIFORNIA SUR'), ('27', 'TABASCO'), ('31', 'YUCATÁN'), ('18', 'NAYARIT'), ('06', 'COLIMA'), ('08', 'CHIHUAHUA'), ('22', 'QUERÉTARO'), ('05', 'COAHUILA DE ZARAGOZA'), ('97', 'NO APLICA'), ('15', 'MÉXICO'), ('04', 'CAMPECHE'), ('02', 'BAJA CALIFORNIA'), ('26', 'SONORA'), ('11', 'GUANAJUATO'), ('98', 'SE IGNORA'), ('23', 'QUINTANA ROO'), ('28', 'TAMAULIPAS'), ('99', 'NO ESPECIFICADO'), ('32', 'ZACATECAS')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_UM',
            field=models.CharField(choices=[('14', 'JALISCO'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('24', 'SAN LUIS POTOSÍ'), ('01', 'AGUASCALIENTES'), ('25', 'SINALOA'), ('07', 'CHIAPAS'), ('21', 'PUEBLA'), ('09', 'CIUDAD DE MÉXICO'), ('12', 'GUERRERO'), ('13', 'HIDALGO'), ('29', 'TLAXCALA'), ('16', 'MICHOACÁN DE OCAMPO'), ('19', 'NUEVO LEÓN'), ('17', 'MORELOS'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('10', 'DURANGO'), ('20', 'OAXACA'), ('03', 'BAJA CALIFORNIA SUR'), ('27', 'TABASCO'), ('31', 'YUCATÁN'), ('18', 'NAYARIT'), ('06', 'COLIMA'), ('08', 'CHIHUAHUA'), ('22', 'QUERÉTARO'), ('05', 'COAHUILA DE ZARAGOZA'), ('97', 'NO APLICA'), ('15', 'MÉXICO'), ('04', 'CAMPECHE'), ('02', 'BAJA CALIFORNIA'), ('26', 'SONORA'), ('11', 'GUANAJUATO'), ('98', 'SE IGNORA'), ('23', 'QUINTANA ROO'), ('28', 'TAMAULIPAS'), ('99', 'NO ESPECIFICADO'), ('32', 'ZACATECAS')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EPOC',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HABLA_LENGUA_INDIG',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HIPERTENSION',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INMUSUPR',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INTUBADO',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='MIGRANTE',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NACIONALIDAD',
            field=models.CharField(choices=[('1', 'mexicana'), ('2', 'extranjera'), ('99', 'no especificado')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NEUMONIA',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OBESIDAD',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ORIGEN',
            field=models.CharField(choices=[('2', 'FUERA DE USMER'), ('1', 'USMER'), ('99', 'NO ESPECIFICADO')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRA_COM',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRO_CASO',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='PAIS_ORIGEN',
            field=models.CharField(choices=[('1', 'mexicana'), ('2', 'extranjera'), ('99', 'no especificado')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RENAL_CRONICA',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RESULTADO',
            field=models.CharField(choices=[('2', 'no positivo SARS-CoV-2'), ('99', 'resultado pendiente'), ('1', 'positivo SARS-CoV-2')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SECTOR',
            field=models.CharField(choices=[('11', 'SEMAR'), ('2', 'DIF'), ('13', 'UNIVERSITARIO'), ('7', 'MUNICIPAL'), ('10', 'SEDENA'), ('12', 'SSA'), ('9', 'PRIVADA'), ('1', 'CRUZ ROJA'), ('5', 'IMSS-BIENESTAR'), ('99', 'NO ESPECIFICADO'), ('4', 'IMSS'), ('6', 'ISSSTE'), ('3', 'ESTATAL'), ('8', 'PEMEX')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SEXO',
            field=models.CharField(choices=[('2', 'hombre'), ('1', 'mujer'), ('99', 'NO ESPECIFICADO')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TABAQUISMO',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TIPO_PACIENTE',
            field=models.CharField(choices=[('2', 'HOSPITALZADO'), ('99', 'NO ESPECIFICADO'), ('1', 'AMBULATORIA')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='UCI',
            field=models.CharField(choices=[('2', 'no'), ('97', 'no aplica'), ('99', 'no especificado'), ('1', 'si'), ('98', 'se ignora')], default='1', max_length=2),
        ),
        migrations.DeleteModel(
            name='origen',
        ),
        migrations.DeleteModel(
            name='sector',
        ),
        migrations.DeleteModel(
            name='sexo',
        ),
        migrations.DeleteModel(
            name='tipo_paciente',
        ),
        migrations.AddField(
            model_name='municipios',
            name='clave_estado',
            field=models.ForeignKey(default='99', on_delete=django.db.models.deletion.CASCADE, to='covidIA.estados'),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_RES',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidIA.estados'),
        ),
    ]
