# Generated by Django 4.2.5 on 2023-10-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidIA', '0003_estados_delete_resultado_alter_setdatos_asma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='clave',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ASMA',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='CARDIOVASCULAR',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='DIABETES',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EMBARAZO',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_NAC',
            field=models.CharField(choices=[('08', 'CHIHUAHUA'), ('09', 'CIUDAD DE MÉXICO'), ('12', 'GUERRERO'), ('24', 'SAN LUIS POTOSÍ'), ('17', 'MORELOS'), ('01', 'AGUASCALIENTES'), ('26', 'SONORA'), ('20', 'OAXACA'), ('16', 'MICHOACÁN DE OCAMPO'), ('10', 'DURANGO'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('22', 'QUERÉTARO'), ('21', 'PUEBLA'), ('14', 'JALISCO'), ('29', 'TLAXCALA'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('25', 'SINALOA'), ('07', 'CHIAPAS'), ('32', 'ZACATECAS'), ('19', 'NUEVO LEÓN'), ('99', 'NO ESPECIFICADO'), ('11', 'GUANAJUATO'), ('04', 'CAMPECHE'), ('18', 'NAYARIT'), ('03', 'BAJA CALIFORNIA SUR'), ('23', 'QUINTANA ROO'), ('28', 'TAMAULIPAS'), ('05', 'COAHUILA DE ZARAGOZA'), ('27', 'TABASCO'), ('15', 'MÉXICO'), ('02', 'BAJA CALIFORNIA'), ('31', 'YUCATÁN'), ('98', 'SE IGNORA'), ('06', 'COLIMA'), ('97', 'NO APLICA'), ('13', 'HIDALGO')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_UM',
            field=models.CharField(choices=[('08', 'CHIHUAHUA'), ('09', 'CIUDAD DE MÉXICO'), ('12', 'GUERRERO'), ('24', 'SAN LUIS POTOSÍ'), ('17', 'MORELOS'), ('01', 'AGUASCALIENTES'), ('26', 'SONORA'), ('20', 'OAXACA'), ('16', 'MICHOACÁN DE OCAMPO'), ('10', 'DURANGO'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('22', 'QUERÉTARO'), ('21', 'PUEBLA'), ('14', 'JALISCO'), ('29', 'TLAXCALA'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('25', 'SINALOA'), ('07', 'CHIAPAS'), ('32', 'ZACATECAS'), ('19', 'NUEVO LEÓN'), ('99', 'NO ESPECIFICADO'), ('11', 'GUANAJUATO'), ('04', 'CAMPECHE'), ('18', 'NAYARIT'), ('03', 'BAJA CALIFORNIA SUR'), ('23', 'QUINTANA ROO'), ('28', 'TAMAULIPAS'), ('05', 'COAHUILA DE ZARAGOZA'), ('27', 'TABASCO'), ('15', 'MÉXICO'), ('02', 'BAJA CALIFORNIA'), ('31', 'YUCATÁN'), ('98', 'SE IGNORA'), ('06', 'COLIMA'), ('97', 'NO APLICA'), ('13', 'HIDALGO')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EPOC',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HABLA_LENGUA_INDIG',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HIPERTENSION',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INMUSUPR',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INTUBADO',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='MIGRANTE',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NACIONALIDAD',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'extranjera'), ('1', 'mexicana')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NEUMONIA',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OBESIDAD',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ORIGEN',
            field=models.CharField(choices=[('1', 'USMER'), ('99', 'NO ESPECIFICADO'), ('2', 'FUERA DE USMER')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRA_COM',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRO_CASO',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='PAIS_ORIGEN',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'extranjera'), ('1', 'mexicana')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RENAL_CRONICA',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RESULTADO',
            field=models.CharField(choices=[('1', 'positivo SARS-CoV-2'), ('2', 'no positivo SARS-CoV-2'), ('99', 'resultado pendiente')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SECTOR',
            field=models.CharField(choices=[('4', 'IMSS'), ('9', 'PRIVADA'), ('6', 'ISSSTE'), ('12', 'SSA'), ('1', 'CRUZ ROJA'), ('13', 'UNIVERSITARIO'), ('2', 'DIF'), ('8', 'PEMEX'), ('11', 'SEMAR'), ('3', 'ESTATAL'), ('10', 'SEDENA'), ('99', 'NO ESPECIFICADO'), ('5', 'IMSS-BIENESTAR'), ('7', 'MUNICIPAL')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SEXO',
            field=models.CharField(choices=[('2', 'hombre'), ('99', 'NO ESPECIFICADO'), ('1', 'mujer')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TABAQUISMO',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TIPO_PACIENTE',
            field=models.CharField(choices=[('1', 'AMBULATORIA'), ('2', 'HOSPITALZADO'), ('99', 'NO ESPECIFICADO')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='UCI',
            field=models.CharField(choices=[('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('99', 'no especificado')], default='1', max_length=2),
        ),
    ]
