# Generated by Django 4.2.5 on 2023-10-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidIA', '0006_alter_setdatos_asma_alter_setdatos_cardiovascular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setdatos',
            name='ASMA',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='CARDIOVASCULAR',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='DIABETES',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EMBARAZO',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_NAC',
            field=models.CharField(choices=[('16', 'MICHOACÁN DE OCAMPO'), ('3', 'BAJA CALIFORNIA SUR'), ('24', 'SAN LUIS POTOSÍ'), ('25', 'SINALOA'), ('11', 'GUANAJUATO'), ('5', 'COAHUILA DE ZARAGOZA'), ('19', 'NUEVO LEÓN'), ('2', 'BAJA CALIFORNIA'), ('12', 'GUERRERO'), ('98', 'SE IGNORA'), ('29', 'TLAXCALA'), ('99', 'NO ESPECIFICADO'), ('26', 'SONORA'), ('10', 'DURANGO'), ('22', 'QUERÉTARO'), ('31', 'YUCATÁN'), ('20', 'OAXACA'), ('23', 'QUINTANA ROO'), ('21', 'PUEBLA'), ('13', 'HIDALGO'), ('27', 'TABASCO'), ('18', 'NAYARIT'), ('1', 'AGUASCALIENTES'), ('8', 'CHIHUAHUA'), ('14', 'JALISCO'), ('7', 'CHIAPAS'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('17', 'MORELOS'), ('9', 'CIUDAD DE MÉXICO'), ('6', 'COLIMA'), ('15', 'MÉXICO'), ('32', 'ZACATECAS'), ('4', 'CAMPECHE'), ('28', 'TAMAULIPAS'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('97', 'NO APLICA')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_UM',
            field=models.CharField(choices=[('16', 'MICHOACÁN DE OCAMPO'), ('3', 'BAJA CALIFORNIA SUR'), ('24', 'SAN LUIS POTOSÍ'), ('25', 'SINALOA'), ('11', 'GUANAJUATO'), ('5', 'COAHUILA DE ZARAGOZA'), ('19', 'NUEVO LEÓN'), ('2', 'BAJA CALIFORNIA'), ('12', 'GUERRERO'), ('98', 'SE IGNORA'), ('29', 'TLAXCALA'), ('99', 'NO ESPECIFICADO'), ('26', 'SONORA'), ('10', 'DURANGO'), ('22', 'QUERÉTARO'), ('31', 'YUCATÁN'), ('20', 'OAXACA'), ('23', 'QUINTANA ROO'), ('21', 'PUEBLA'), ('13', 'HIDALGO'), ('27', 'TABASCO'), ('18', 'NAYARIT'), ('1', 'AGUASCALIENTES'), ('8', 'CHIHUAHUA'), ('14', 'JALISCO'), ('7', 'CHIAPAS'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('17', 'MORELOS'), ('9', 'CIUDAD DE MÉXICO'), ('6', 'COLIMA'), ('15', 'MÉXICO'), ('32', 'ZACATECAS'), ('4', 'CAMPECHE'), ('28', 'TAMAULIPAS'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('97', 'NO APLICA')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EPOC',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HABLA_LENGUA_INDIG',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HIPERTENSION',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INMUSUPR',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INTUBADO',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='MIGRANTE',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NACIONALIDAD',
            field=models.CharField(choices=[('2', 'extranjera'), ('99', 'no especificado'), ('1', 'mexicana')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NEUMONIA',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OBESIDAD',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ORIGEN',
            field=models.CharField(choices=[('99', 'NO ESPECIFICADO'), ('1', 'USMER'), ('2', 'FUERA DE USMER')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRA_COM',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRO_CASO',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='PAIS_ORIGEN',
            field=models.CharField(choices=[('2', 'extranjera'), ('99', 'no especificado'), ('1', 'mexicana')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RENAL_CRONICA',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SECTOR',
            field=models.CharField(choices=[('7', 'MUNICIPAL'), ('8', 'PEMEX'), ('4', 'IMSS'), ('13', 'UNIVERSITARIO'), ('6', 'ISSSTE'), ('99', 'NO ESPECIFICADO'), ('9', 'PRIVADA'), ('11', 'SEMAR'), ('12', 'SSA'), ('5', 'IMSS-BIENESTAR'), ('10', 'SEDENA'), ('3', 'ESTATAL'), ('2', 'DIF'), ('1', 'CRUZ ROJA')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TABAQUISMO',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TIPO_PACIENTE',
            field=models.CharField(choices=[('2', 'HOSPITALZADO'), ('99', 'NO ESPECIFICADO'), ('1', 'AMBULATORIA')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='UCI',
            field=models.CharField(choices=[('97', 'no aplica'), ('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('2', 'no')], default='1', max_length=2),
        ),
    ]
