# Generated by Django 4.2.5 on 2023-10-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidIA', '0007_alter_setdatos_asma_alter_setdatos_cardiovascular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setdatos',
            name='ASMA',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='CARDIOVASCULAR',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='DIABETES',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EMBARAZO',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_NAC',
            field=models.CharField(choices=[('5', 'COAHUILA DE ZARAGOZA'), ('17', 'MORELOS'), ('23', 'QUINTANA ROO'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('97', 'NO APLICA'), ('18', 'NAYARIT'), ('8', 'CHIHUAHUA'), ('26', 'SONORA'), ('12', 'GUERRERO'), ('7', 'CHIAPAS'), ('10', 'DURANGO'), ('20', 'OAXACA'), ('22', 'QUERÉTARO'), ('19', 'NUEVO LEÓN'), ('6', 'COLIMA'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('3', 'BAJA CALIFORNIA SUR'), ('99', 'NO ESPECIFICADO'), ('1', 'AGUASCALIENTES'), ('24', 'SAN LUIS POTOSÍ'), ('31', 'YUCATÁN'), ('32', 'ZACATECAS'), ('4', 'CAMPECHE'), ('29', 'TLAXCALA'), ('28', 'TAMAULIPAS'), ('27', 'TABASCO'), ('16', 'MICHOACÁN DE OCAMPO'), ('14', 'JALISCO'), ('98', 'SE IGNORA'), ('9', 'CIUDAD DE MÉXICO'), ('15', 'MÉXICO'), ('2', 'BAJA CALIFORNIA'), ('11', 'GUANAJUATO'), ('13', 'HIDALGO'), ('21', 'PUEBLA'), ('25', 'SINALOA')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_UM',
            field=models.CharField(choices=[('5', 'COAHUILA DE ZARAGOZA'), ('17', 'MORELOS'), ('23', 'QUINTANA ROO'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('97', 'NO APLICA'), ('18', 'NAYARIT'), ('8', 'CHIHUAHUA'), ('26', 'SONORA'), ('12', 'GUERRERO'), ('7', 'CHIAPAS'), ('10', 'DURANGO'), ('20', 'OAXACA'), ('22', 'QUERÉTARO'), ('19', 'NUEVO LEÓN'), ('6', 'COLIMA'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('3', 'BAJA CALIFORNIA SUR'), ('99', 'NO ESPECIFICADO'), ('1', 'AGUASCALIENTES'), ('24', 'SAN LUIS POTOSÍ'), ('31', 'YUCATÁN'), ('32', 'ZACATECAS'), ('4', 'CAMPECHE'), ('29', 'TLAXCALA'), ('28', 'TAMAULIPAS'), ('27', 'TABASCO'), ('16', 'MICHOACÁN DE OCAMPO'), ('14', 'JALISCO'), ('98', 'SE IGNORA'), ('9', 'CIUDAD DE MÉXICO'), ('15', 'MÉXICO'), ('2', 'BAJA CALIFORNIA'), ('11', 'GUANAJUATO'), ('13', 'HIDALGO'), ('21', 'PUEBLA'), ('25', 'SINALOA')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EPOC',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HABLA_LENGUA_INDIG',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HIPERTENSION',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INMUSUPR',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INTUBADO',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='MIGRANTE',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NACIONALIDAD',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'extranjera'), ('1', 'mexicana')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NEUMONIA',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OBESIDAD',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ORIGEN',
            field=models.CharField(choices=[('99', 'NO ESPECIFICADO'), ('2', 'FUERA DE USMER'), ('1', 'USMER')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRA_COM',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRO_CASO',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='PAIS_ORIGEN',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'extranjera'), ('1', 'mexicana')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RENAL_CRONICA',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RESULTADO',
            field=models.CharField(choices=[('1', 'positivo SARS-CoV-2'), ('99', 'resultado pendiente'), ('2', 'no positivo SARS-CoV-2')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SECTOR',
            field=models.CharField(choices=[('9', 'PRIVADA'), ('12', 'SSA'), ('8', 'PEMEX'), ('7', 'MUNICIPAL'), ('11', 'SEMAR'), ('6', 'ISSSTE'), ('13', 'UNIVERSITARIO'), ('10', 'SEDENA'), ('99', 'NO ESPECIFICADO'), ('1', 'CRUZ ROJA'), ('3', 'ESTATAL'), ('4', 'IMSS'), ('5', 'IMSS-BIENESTAR'), ('2', 'DIF')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SEXO',
            field=models.CharField(choices=[('2', 'hombre'), ('1', 'mujer'), ('99', 'NO ESPECIFICADO')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TABAQUISMO',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TIPO_PACIENTE',
            field=models.CharField(choices=[('99', 'NO ESPECIFICADO'), ('1', 'AMBULATORIA'), ('2', 'HOSPITALZADO')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='UCI',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica'), ('1', 'si')], default='1', max_length=2),
        ),
    ]
