# Generated by Django 4.2.5 on 2023-10-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidIA', '0008_alter_setdatos_asma_alter_setdatos_cardiovascular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setdatos',
            name='ASMA',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='CARDIOVASCULAR',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='DIABETES',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EMBARAZO',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_NAC',
            field=models.CharField(choices=[('7', 'CHIAPAS'), ('16', 'MICHOACÁN DE OCAMPO'), ('31', 'YUCATÁN'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('24', 'SAN LUIS POTOSÍ'), ('26', 'SONORA'), ('99', 'NO ESPECIFICADO'), ('27', 'TABASCO'), ('14', 'JALISCO'), ('29', 'TLAXCALA'), ('5', 'COAHUILA DE ZARAGOZA'), ('1', 'AGUASCALIENTES'), ('2', 'BAJA CALIFORNIA'), ('6', 'COLIMA'), ('32', 'ZACATECAS'), ('17', 'MORELOS'), ('20', 'OAXACA'), ('22', 'QUERÉTARO'), ('98', 'SE IGNORA'), ('13', 'HIDALGO'), ('4', 'CAMPECHE'), ('28', 'TAMAULIPAS'), ('97', 'NO APLICA'), ('9', 'CIUDAD DE MÉXICO'), ('3', 'BAJA CALIFORNIA SUR'), ('10', 'DURANGO'), ('18', 'NAYARIT'), ('15', 'MÉXICO'), ('12', 'GUERRERO'), ('8', 'CHIHUAHUA'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('11', 'GUANAJUATO'), ('25', 'SINALOA'), ('19', 'NUEVO LEÓN'), ('21', 'PUEBLA'), ('23', 'QUINTANA ROO')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_UM',
            field=models.CharField(choices=[('7', 'CHIAPAS'), ('16', 'MICHOACÁN DE OCAMPO'), ('31', 'YUCATÁN'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('24', 'SAN LUIS POTOSÍ'), ('26', 'SONORA'), ('99', 'NO ESPECIFICADO'), ('27', 'TABASCO'), ('14', 'JALISCO'), ('29', 'TLAXCALA'), ('5', 'COAHUILA DE ZARAGOZA'), ('1', 'AGUASCALIENTES'), ('2', 'BAJA CALIFORNIA'), ('6', 'COLIMA'), ('32', 'ZACATECAS'), ('17', 'MORELOS'), ('20', 'OAXACA'), ('22', 'QUERÉTARO'), ('98', 'SE IGNORA'), ('13', 'HIDALGO'), ('4', 'CAMPECHE'), ('28', 'TAMAULIPAS'), ('97', 'NO APLICA'), ('9', 'CIUDAD DE MÉXICO'), ('3', 'BAJA CALIFORNIA SUR'), ('10', 'DURANGO'), ('18', 'NAYARIT'), ('15', 'MÉXICO'), ('12', 'GUERRERO'), ('8', 'CHIHUAHUA'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('11', 'GUANAJUATO'), ('25', 'SINALOA'), ('19', 'NUEVO LEÓN'), ('21', 'PUEBLA'), ('23', 'QUINTANA ROO')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EPOC',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='FECHA_ACTUALIZACION',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HABLA_LENGUA_INDIG',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HIPERTENSION',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INMUSUPR',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INTUBADO',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='MIGRANTE',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NACIONALIDAD',
            field=models.CharField(choices=[('1', 'mexicana'), ('2', 'extranjera'), ('99', 'no especificado')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NEUMONIA',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OBESIDAD',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ORIGEN',
            field=models.CharField(choices=[('1', 'USMER'), ('99', 'NO ESPECIFICADO'), ('2', 'FUERA DE USMER')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRA_COM',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRO_CASO',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='PAIS_ORIGEN',
            field=models.CharField(choices=[('1', 'mexicana'), ('2', 'extranjera'), ('99', 'no especificado')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RENAL_CRONICA',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RESULTADO',
            field=models.CharField(choices=[('1', 'positivo SARS-CoV-2'), ('2', 'no positivo SARS-CoV-2'), ('99', 'resultado pendiente')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SECTOR',
            field=models.CharField(choices=[('3', 'ESTATAL'), ('2', 'DIF'), ('12', 'SSA'), ('10', 'SEDENA'), ('4', 'IMSS'), ('11', 'SEMAR'), ('1', 'CRUZ ROJA'), ('6', 'ISSSTE'), ('99', 'NO ESPECIFICADO'), ('9', 'PRIVADA'), ('7', 'MUNICIPAL'), ('13', 'UNIVERSITARIO'), ('5', 'IMSS-BIENESTAR'), ('8', 'PEMEX')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SEXO',
            field=models.CharField(choices=[('1', 'mujer'), ('99', 'NO ESPECIFICADO'), ('2', 'hombre')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TABAQUISMO',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TIPO_PACIENTE',
            field=models.CharField(choices=[('99', 'NO ESPECIFICADO'), ('2', 'HOSPITALZADO'), ('1', 'AMBULATORIA')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='UCI',
            field=models.CharField(choices=[('99', 'no especificado'), ('1', 'si'), ('2', 'no'), ('98', 'se ignora'), ('97', 'no aplica')], default='1', max_length=2),
        ),
    ]
