# Generated by Django 4.2.5 on 2023-10-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidIA', '0011_alter_setdatos_asma_alter_setdatos_cardiovascular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setdatos',
            name='ASMA',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='CARDIOVASCULAR',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='DIABETES',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EDAD',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EMBARAZO',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_NAC',
            field=models.CharField(choices=[('10', 'DURANGO'), ('11', 'GUANAJUATO'), ('21', 'PUEBLA'), ('24', 'SAN LUIS POTOSÍ'), ('12', 'GUERRERO'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('4', 'CAMPECHE'), ('19', 'NUEVO LEÓN'), ('31', 'YUCATÁN'), ('1', 'AGUASCALIENTES'), ('16', 'MICHOACÁN DE OCAMPO'), ('98', 'SE IGNORA'), ('23', 'QUINTANA ROO'), ('97', 'NO APLICA'), ('9', 'CIUDAD DE MÉXICO'), ('32', 'ZACATECAS'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('99', 'NO ESPECIFICADO'), ('17', 'MORELOS'), ('29', 'TLAXCALA'), ('8', 'CHIHUAHUA'), ('18', 'NAYARIT'), ('15', 'MÉXICO'), ('2', 'BAJA CALIFORNIA'), ('7', 'CHIAPAS'), ('5', 'COAHUILA DE ZARAGOZA'), ('6', 'COLIMA'), ('22', 'QUERÉTARO'), ('27', 'TABASCO'), ('14', 'JALISCO'), ('20', 'OAXACA'), ('13', 'HIDALGO'), ('3', 'BAJA CALIFORNIA SUR'), ('28', 'TAMAULIPAS'), ('25', 'SINALOA'), ('26', 'SONORA')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='ENTIDAD_UM',
            field=models.CharField(choices=[('10', 'DURANGO'), ('11', 'GUANAJUATO'), ('21', 'PUEBLA'), ('24', 'SAN LUIS POTOSÍ'), ('12', 'GUERRERO'), ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE'), ('4', 'CAMPECHE'), ('19', 'NUEVO LEÓN'), ('31', 'YUCATÁN'), ('1', 'AGUASCALIENTES'), ('16', 'MICHOACÁN DE OCAMPO'), ('98', 'SE IGNORA'), ('23', 'QUINTANA ROO'), ('97', 'NO APLICA'), ('9', 'CIUDAD DE MÉXICO'), ('32', 'ZACATECAS'), ('36', 'ESTADOS UNIDOS MEXICANOS'), ('99', 'NO ESPECIFICADO'), ('17', 'MORELOS'), ('29', 'TLAXCALA'), ('8', 'CHIHUAHUA'), ('18', 'NAYARIT'), ('15', 'MÉXICO'), ('2', 'BAJA CALIFORNIA'), ('7', 'CHIAPAS'), ('5', 'COAHUILA DE ZARAGOZA'), ('6', 'COLIMA'), ('22', 'QUERÉTARO'), ('27', 'TABASCO'), ('14', 'JALISCO'), ('20', 'OAXACA'), ('13', 'HIDALGO'), ('3', 'BAJA CALIFORNIA SUR'), ('28', 'TAMAULIPAS'), ('25', 'SINALOA'), ('26', 'SONORA')], default='99', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='EPOC',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='FECHA_DEF',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='FECHA_INGRESO',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='FECHA_SINTOMAS',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HABLA_LENGUA_INDIG',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='HIPERTENSION',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INMUSUPR',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='INTUBADO',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='MIGRANTE',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NACIONALIDAD',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'extranjera'), ('1', 'mexicana')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='NEUMONIA',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OBESIDAD',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRA_COM',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='OTRO_CASO',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='PAIS_NACIONALIDAD',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='PAIS_ORIGEN',
            field=models.CharField(choices=[('99', 'no especificado'), ('2', 'extranjera'), ('1', 'mexicana')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RENAL_CRONICA',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='RESULTADO',
            field=models.CharField(choices=[('2', 'no positivo SARS-CoV-2'), ('99', 'resultado pendiente'), ('1', 'positivo SARS-CoV-2')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SECTOR',
            field=models.CharField(choices=[('11', 'SEMAR'), ('8', 'PEMEX'), ('10', 'SEDENA'), ('6', 'ISSSTE'), ('9', 'PRIVADA'), ('99', 'NO ESPECIFICADO'), ('4', 'IMSS'), ('5', 'IMSS-BIENESTAR'), ('2', 'DIF'), ('12', 'SSA'), ('13', 'UNIVERSITARIO'), ('7', 'MUNICIPAL'), ('3', 'ESTATAL'), ('1', 'CRUZ ROJA')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='SEXO',
            field=models.CharField(choices=[('99', 'NO ESPECIFICADO'), ('1', 'mujer'), ('2', 'hombre')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TABAQUISMO',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='TIPO_PACIENTE',
            field=models.CharField(choices=[('99', 'NO ESPECIFICADO'), ('1', 'AMBULATORIA'), ('2', 'HOSPITALZADO')], default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='setdatos',
            name='UCI',
            field=models.CharField(choices=[('1', 'si'), ('98', 'se ignora'), ('99', 'no especificado'), ('97', 'no aplica'), ('2', 'no')], default='1', max_length=2),
        ),
    ]
